spring:
  application:
    name: cash-service
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: ${CONSUL.HOST}
      port: ${CONSUL.PORT}
      discovery:
        enabled: true
        service-name: cash-service
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
      config:
        enabled: true
        format: YAML
        prefix: config
        default-context: application
        fail-fast: true
        watch:
          enabled: true
          delay: 1000

