openapi: 3.0.3
info:
  title: Сервис пополнения или снятия
  version: 1.0.0-SNAPSHOT

paths:
  /action:
    post:
      operationId: Cash
      summary: Пополнение или снятие счета
      tags:
        - cash
      description: Данные из UI формы передаются в систему и передаются в account-service и сохраняются в БД
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CashDto'
      responses:
        "200":
          description: "Операция успешно завершена"
          content:
            application/json:
              schema:
                type: string
        "400":
          description: "Ошибка при работес счетом"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CashDto:
      type: object
      properties:
        keycloakId:
          type: string
          description: Идентификатор пользователя в Keycloak
        value:
          type: string
          description: сумма денег
        action:
          type: string
          description: пополнение или снятие