spring:
  application:
    name: front-ui
  config:
    import: "optional:consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        service-name: front-ui
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
      config:
        enabled: true
        format: YAML
        prefix: config
        default-context: application
        fail-fast: true
        watch:
          enabled: true
          delay: 1000

