spring:
  config:
    import: "optional:consul:"
  application:
    name: front-ui
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: false  # Временно отключите Consul для простоты
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://${keycloak-custom.host}:${keycloak-custom.port}/realms/master
            user-name-attribute: preferred_username  # Лучше чем "sub"
        registration:
          front-ui:
            provider: keycloak
            client-id: front-ui
            client-secret: UtEeKuE25MilWrxKqbxzCDoO0Pto8uKe
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/front-ui"  # Конкретный URI
            scope:
              - openid
              - profile
              - email
            client-authentication-method: client_secret_basic  # Лучше чем post

keycloak-custom:
  host: localhost
  port: 9090

server:
  port: 8080  # Явно укажите порт

management:
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework.security: DEBUG